import 'tailwindcss/tailwind.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className='dark' lang='es'>
      <body
        className={`bg-gradient-to-r from-color-four via-color-three to-color-two dark:bg-gradient-to-r dark:from-color-one dark:via-color-two dark:to-color-three ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
