import 'tailwindcss/tailwind.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className='dark' lang='es'>
      <body
        className={`bg-dark-home dark:bg-gradient-to-r dark:from-color-one dark:via-color-three dark:to-color-one`}
      >
        {children}
      </body>
    </html>
  );
}
